#!/bin/bash
#------------------------------------------////
# FUNCTIONS:
#------------------------------------------////

mkdircd() {
    mkdir $1 && cd $1 || exit 1
}

createrepo() {
    curl -X POST -H "Authorization: token "$token"" -d  '{ "name": "'"$2"'"}' "https://api.github.com/orgs/"$1"/repos"
}

sync() {
    if [ -d .repo ]; then
        time repo sync -f -c --no-clone-bundle -j32 --no-tags $@
    else
        cd ${HOME}/$1; time repo sync -f -c --no-clone-bundle -j32 --no-tags
    fi
}

keygen() {
    ssh-keygen -t rsa -b 4096 -C $1
}

tlpmode() {
    batterystate=$(acpi | sed 's/^.*Discharging/Discharging/; s/Discharging.*/Discharging/')

    if [[ $batterystate = 'Discharging' ]]; then
      sudo tlp bat
    else
      sudo tlp ac
    fi

}

updategrub() {
    sudo grub-mkconfig -o /boot/grub/grub.cfg
}

genapplist() {
    comm -23 <(apt-mark showmanual | sort -u) <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort -u)
}

fm() {
    nautilus .
}

gapp() {
    ps aux | grep $1
}
