#!/usr/bin/env bash
source ${HOME}/bin/env
DATE=`date +%Y`
jobcount="-j$(grep -c ^processor /proc/cpuinfo)"
ROM="$1"
DEVICE="$2"
COMMAND="$3"

cd ${HOME}/${ROM}
source build/envsetup.sh

if [[ "$COMMAND" = "clean" ]]; then
make clobber
make clean
fi

if [[ "$COMMAND" =~ "dirty" ]]; then
make installclean
outdir="./out/target/product/${DEVICE}";
  rm -rf "$outdir/combinedroot";
  rm -rf "$outdir/data";
  rm -rf "$outdir/recovery";
  rm -rf "$outdir/root";
  rm -rf "$outdir/system";
  rm -rf "$outdir/utilities";
  rm -rf "$outdir/boot"*;
  rm -rf "$outdir/combined"*;
  rm -rf "$outdir/kernel";
  rm -rf "$outdir/ramdisk"*;
  rm -rf "$outdir/recovery"*;
  rm -rf "$outdir/system"*;
  rm -rf "$outdir/obj/ETC/system_build_prop_intermediates";
  rm -rf "$outdir/ota_temp/RECOVERY/RAMDISK";
fi

if [[ "$COMMAND" =~ "sync" ]]; then
time repo sync -f -c --no-clone-bundle -j128 --no-tags
fi

#if [ ! -d ${HOME}/.ccache-${DEVICE}_${ROM} ] ; then
#mkdir ${HOME}/.ccache-${DEVICE}_${ROM}
#fi

export CCACHE_DIR=${HOME}/.ccache
export USE_CCACHE=0
#ccache -M 50G
./prebuilts/misc/linux-x86/ccache/ccache -M 50

breakfast ${DEVICE}
time make $jobcount bacon
if [ $? -eq 0 ]; then
    cd $OUT
    if [[ "$ROM" = "deso" ]]; then
        ROM_ZIP="$(ls Desolation*${DATE}*.zip | awk '{print $1}')"
        FOLDER_ID="0B2HoiwlM3QDxVEo0LWNuZ0paYWc"
    elif [[ "$ROM" = "fork" ]]; then
        ROM_ZIP="$(ls *fork*${DEVICE}*.zip | awk '{print $1}')"
        FOLDER_ID="$0B2HoiwlM3QDxXzV6OTFfb0szZXc"
    elif [[ "$ROM" = "aicp" ]]; then
        ROM_ZIP="$(ls aicp*${DEVICE}*.zip | awk '{print $1}')"
        FOLDER_ID="0B2HoiwlM3QDxVFk4UUd2bG56Ums"
    else
        ROM_ZIP="$(ls *${DATE}*.zip | awk '{print $1}')"
        FOLDER_ID="0B2HoiwlM3QDxOGc0SE9jLUYwdTA"
    fi
    rm out/target/product/${DEVICE}/*.zip*
#    FILE_ID="$(gdrive list | grep ${ROM} | awk '{print $2}'| tail -1}"
#    DOWNLOAD_URL="$(drive share -i ${FILE_ID)"
    DOWNLOAD_URL="$(drive upload -f ${ROM_ZIP} -p ${FOLDER_ID} --share | tail -1 | awk '{print $9}')"
    echo "[${ROM_ZIP}](${DOWNLOAD_URL})" >> ~/velvet/builderbot/romlink.txt
fi
