#!/bin/bash
ROOT="${PWD}"
CMREMOTE=$(cat .git/config  | grep git://github.com | awk '{ print $NF }' | sed s#git://github.com/##g)

LOCALDIR=(
    'build'
    'frameworks/base'
    'frameworks/native'
    'packages/apps/Contacts'
    'packages/apps/ContactsCommon'
    'packages/apps/Dialer'
    'packages/apps/ExactCalculator'
    'packages/apps/PackageInstaller'
    'packages/apps/PhoneCommon'
    'packages/apps/Settings'
    'packages/apps/CMParts'
    'system/sepolicy'
    'system/core'
    'system/netd'
    'vendor/cm'
    'vendor/cmsdk'
)

for local in "${LOCALDIR[@]}"; do
    cd "${ROOT}/${local}"

    if [ ! -d .git ]
    then
        echo .git directory not found. Please run this from the root directory of the Android repository you wish to set up.
    fi

    git remote add los $(git remote -v | grep lineagefork | awk '{print $2}' | sed -e 's|lineagefork/|lineageos/|' | uniq)
    git fetch los; git merge los/cm-14.1
    git push $(git remote -v | grep lineagefork | awk '{print $2}' | sed -e 's|git://github.com/|git@github.com:|' | uniq) HEAD:cm-14.1
done
